server {
    listen 80;
    server_name test.demo.com;
    root /usr/share/nginx/html;
    index index.html index.php;
    #基础安全加固
    server_tokens off:
    client_max_body_size 10M;
    location ~/\. {
        deny all;
   }
  #php解析设置
    location ~\.php$ {
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params:
  }
}
